version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: menuboxgh-db
    environment:
      POSTGRES_USER: menuboxgh
      POSTGRES_PASSWORD: menuboxgh123
      POSTGRES_DB: menuboxgh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
